syntax = "proto3";
package resume.v1;

option go_package = "github.com/Raaihhan/resume-gateway/gen/go/proto/resume/v1;resumev1";


import "google/protobuf/empty.proto";

message GetProfileRequest {}

message Profile {
  string full_name   = 1;
  string headline    = 2;
  string summary     = 3;
  string location    = 4;
  repeated string skills = 5;
  string avatar_url  = 6;
}

message Project {
  string id           = 1;
  string name         = 2;
  string description  = 3;
  string repo_url     = 4;
  string demo_url     = 5;
  repeated string tags = 6;
}

message ListProjectsRequest {
  string page_number  = 1;  // 1-based, tetap string
  string page_size    = 2;  // max 100, tetap string
  string search_query = 3;  // kata kunci
}

message ListProjectsResponse {
  repeated Project items = 1;
  string total = 2;         // total items, tetap string
}

message CreateContactMessageRequest {
  string name    = 1;
  string email   = 2;
  string message = 3;
}

message CreateContactMessageResponse {
  string status = 1; // "ok"
}

message LoadHobbyResponse {
  string Tags = 1;
  string Remaks = 2;
  string Description = 3;
}

message ListSkillsResponse {
  string Skills = 1;
  string Description = 2;
  string Years = 3;
}


service ResumeGatewayService {
  rpc GetProfile(GetProfileRequest) returns (Profile);
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
  rpc CreateContactMessage(CreateContactMessageRequest) returns (CreateContactMessageResponse);
  rpc ListHobbies(google.protobuf.Empty) returns (LoadHobbyResponse);
  rpc ListSkills(google.protobuf.Empty) returns (ListSkillsResponse);
}
